var searchData=
[
  ['daemon_0',['Service Daemon',['../md__r_e_a_d_m_e.html',1,'']]],
  ['daily_20workflow_1',['Daily Workflow',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md27',1,'']]],
  ['data_20access_20layer_2',['Core usage (data access layer)',['../md__r_e_a_d_m_e.html#autotoc_md114',1,'']]],
  ['database_3',['Database',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md55',1,'Step 3: Set Up PostgreSQL User and Database'],['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md17',1,'Step 6: Initialize Database'],['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md58',1,'Step 6: Initialize Your Database']]],
  ['database_4',['Test 3: Initialize database',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md90',1,'']]],
  ['database_20configuration_5',['Database configuration',['../md__r_e_a_d_m_e.html#autotoc_md112',1,'']]],
  ['database_20connection_6',['6) Configure your database connection',['../md__r_e_a_d_m_e.html#autotoc_md104',1,'']]],
  ['database_20connection_20errors_7',['Database connection errors?',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md22',1,'']]],
  ['database_20does_20not_20exist_8',['&quot;database does not exist&quot;',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md83',1,'']]],
  ['database_20management_9',['Database Management',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md33',1,'']]],
  ['database_20schema_10',['7) Initialize the database schema',['../md__r_e_a_d_m_e.html#autotoc_md105',1,'']]],
  ['database_3a_11',['Create Database:',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md67',1,'']]],
  ['debian_3a_12',['Ubuntu/Debian:',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md62',1,'']]],
  ['dependencies_13',['Step 3: Install Python Dependencies',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md14',1,'']]],
  ['dependencies_14',['dependencies',['../md_docs_2_q_u_i_c_k___s_t_a_r_t.html#autotoc_md1',1,'1) Install dependencies'],['../md__r_e_a_d_m_e.html#autotoc_md102',1,'4) Install Python dependencies']]],
  ['detail_15',['Need more detail?',['../md__r_e_a_d_m_e.html#autotoc_md119',1,'']]],
  ['detection_20what_20system_20are_20you_20on_16',['Quick Detection - What System Are You On?',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md50',1,'']]],
  ['developers_20try_20the_20example_20usage_17',['8) (optional for developers) Try the example usage',['../md__r_e_a_d_m_e.html#autotoc_md106',1,'']]],
  ['diagnostic_20test_18',['Test 2: Run diagnostic test',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md89',1,'']]],
  ['diagnostics_19',['9) Run diagnostics',['../md__r_e_a_d_m_e.html#autotoc_md107',1,'']]],
  ['docker_20',['Step 1: Run PostgreSQL in Docker',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md75',1,'']]],
  ['docker_20commands_3a_21',['Useful Docker Commands:',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md78',1,'']]],
  ['docker_20easiest_20works_20everywhere_22',['Option 5: Docker (Easiest - Works Everywhere)',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md74',1,'']]],
  ['does_20not_20exist_23',['&quot;database does not exist&quot;',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md83',1,'']]],
  ['download_20and_20install_3a_24',['Download and Install:',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md70',1,'']]]
];
