var searchData=
[
  ['can_20you_20connect_0',['Test 1: Can you connect?',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md88',1,'']]],
  ['centos_3a_1',['Fedora/RHEL/CentOS:',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md63',1,'']]],
  ['changes_2',['Changes',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md30',1,'Committing Changes'],['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md29',1,'Testing Your Changes']]],
  ['checklist_3',['Summary Checklist',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md47',1,'']]],
  ['code_4',['Step 1: Get the Code',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md12',1,'']]],
  ['code_5',['2) Get the code',['../md__r_e_a_d_m_e.html#autotoc_md100',1,'']]],
  ['code_20sample_6',['Minimal code sample',['../md_docs_2_q_u_i_c_k___s_t_a_r_t.html#autotoc_md6',1,'']]],
  ['commands_7',['Common Commands',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md32',1,'']]],
  ['commands_3a_8',['Useful Docker Commands:',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md78',1,'']]],
  ['committing_20changes_9',['Committing Changes',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md30',1,'']]],
  ['common_20commands_10',['Common Commands',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md32',1,'']]],
  ['common_20issues_20and_20solutions_11',['Common Issues and Solutions',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md80',1,'']]],
  ['complete_20setup_20guide_12',['Getting Started - Complete Setup Guide',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html',1,'']]],
  ['configurable_13',['Senior Setup (fast + configurable)',['../md__r_e_a_d_m_e.html#autotoc_md110',1,'']]],
  ['configuration_14',['Database configuration',['../md__r_e_a_d_m_e.html#autotoc_md112',1,'']]],
  ['configuration_20files_15',['Configuration Files',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md39',1,'']]],
  ['configure_20env_16',['Step 3: Configure .env',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md77',1,'']]],
  ['configure_20env_3a_17',['Configure .env:',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md72',1,'']]],
  ['configure_20postgresql_18',['2) Configure PostgreSQL',['../md_docs_2_q_u_i_c_k___s_t_a_r_t.html#autotoc_md2',1,'']]],
  ['configure_20your_20database_20connection_19',['6) Configure your database connection',['../md__r_e_a_d_m_e.html#autotoc_md104',1,'']]],
  ['configure_20your_20env_20file_20',['Step 5: Configure Your .env File',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md57',1,'']]],
  ['connect_21',['Test 1: Can you connect?',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md88',1,'']]],
  ['connect_20to_20server_22',['&quot;Could not connect to server&quot;',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md81',1,'']]],
  ['connection_23',['Step 4: Test Connection',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md56',1,'']]],
  ['connection_24',['6) Configure your database connection',['../md__r_e_a_d_m_e.html#autotoc_md104',1,'']]],
  ['connection_20errors_25',['Database connection errors?',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md22',1,'']]],
  ['core_20usage_20data_20access_20layer_26',['Core usage (data access layer)',['../md__r_e_a_d_m_e.html#autotoc_md114',1,'']]],
  ['could_20not_20connect_20to_20server_27',['&quot;Could not connect to server&quot;',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md81',1,'']]],
  ['create_20a_20virtual_20environment_20recommended_28',['3) Create a virtual environment (recommended)',['../md__r_e_a_d_m_e.html#autotoc_md101',1,'']]],
  ['create_20database_3a_29',['Create Database:',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md67',1,'']]],
  ['credentials_30',['.env (Your Credentials)',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md40',1,'']]]
];
