var searchData=
[
  ['s_20running_0',['Step 2: Verify It&apos;s Running',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md76',1,'']]],
  ['sample_1',['Minimal code sample',['../md_docs_2_q_u_i_c_k___s_t_a_r_t.html#autotoc_md6',1,'']]],
  ['schema_2',['schema',['../md_docs_2_q_u_i_c_k___s_t_a_r_t.html#autotoc_md3',1,'3) Initialize the schema'],['../md__r_e_a_d_m_e.html#autotoc_md105',1,'7) Initialize the database schema']]],
  ['schema_20initialization_3',['Schema + initialization',['../md__r_e_a_d_m_e.html#autotoc_md113',1,'']]],
  ['scripts_4',['Useful scripts',['../md__r_e_a_d_m_e.html#autotoc_md115',1,'']]],
  ['senior_20setup_20fast_20configurable_5',['Senior Setup (fast + configurable)',['../md__r_e_a_d_m_e.html#autotoc_md110',1,'']]],
  ['server_6',['&quot;Could not connect to server&quot;',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md81',1,'']]],
  ['service_7',['Step 2: Start PostgreSQL Service',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md54',1,'']]],
  ['service_20daemon_8',['Service Daemon',['../md__r_e_a_d_m_e.html',1,'']]],
  ['set_20up_20postgresql_9',['Step 4: Set Up PostgreSQL',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md15',1,'']]],
  ['set_20up_20postgresql_10',['5) Set up PostgreSQL',['../md__r_e_a_d_m_e.html#autotoc_md103',1,'']]],
  ['set_20up_20postgresql_20user_20and_20database_11',['Step 3: Set Up PostgreSQL User and Database',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md55',1,'']]],
  ['set_20up_20python_20environment_20recommended_12',['Step 2: Set Up Python Environment (Recommended)',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md13',1,'']]],
  ['setup_13',['Setup',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md16',1,'Step 5: Verify Setup'],['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md87',1,'Testing Your Setup']]],
  ['setup_20fast_20configurable_14',['Senior Setup (fast + configurable)',['../md__r_e_a_d_m_e.html#autotoc_md110',1,'']]],
  ['setup_20guide_15',['Getting Started - Complete Setup Guide',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html',1,'']]],
  ['setup_20step_20by_20step_16',['Novice Setup (step-by-step)',['../md__r_e_a_d_m_e.html#autotoc_md98',1,'']]],
  ['setup_20steps_17',['Setup Steps',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md11',1,'']]],
  ['setup_20wsl_18',['Recommended for Your Setup (WSL)',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md95',1,'']]],
  ['solutions_19',['Common Issues and Solutions',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md80',1,'']]],
  ['sql_20execution_20files_20',['Manual SQL Execution Files',['../dir_f6962ebc6db00250d64de89efe9bc405.html#autotoc_md48',1,'']]],
  ['start_21',['Quick Start',['../md_docs_2_q_u_i_c_k___s_t_a_r_t.html',1,'']]],
  ['start_20postgresql_20on_20wsl_20boot_20optional_22',['Auto-start PostgreSQL on WSL Boot (Optional)',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md59',1,'']]],
  ['start_20postgresql_20service_23',['Step 2: Start PostgreSQL Service',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md54',1,'']]],
  ['started_20complete_20setup_20guide_24',['Getting Started - Complete Setup Guide',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html',1,'']]],
  ['starting_20work_25',['Starting Work',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md28',1,'']]],
  ['step_26',['Novice Setup (step-by-step)',['../md__r_e_a_d_m_e.html#autotoc_md98',1,'']]],
  ['step_201_3a_20get_20the_20code_27',['Step 1: Get the Code',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md12',1,'']]],
  ['step_201_3a_20install_20postgresql_20in_20wsl_28',['Step 1: Install PostgreSQL in WSL',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md53',1,'']]],
  ['step_201_3a_20run_20postgresql_20in_20docker_29',['Step 1: Run PostgreSQL in Docker',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md75',1,'']]],
  ['step_202_3a_20set_20up_20python_20environment_20recommended_30',['Step 2: Set Up Python Environment (Recommended)',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md13',1,'']]],
  ['step_202_3a_20start_20postgresql_20service_31',['Step 2: Start PostgreSQL Service',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md54',1,'']]],
  ['step_202_3a_20verify_20it_20s_20running_32',['Step 2: Verify It&apos;s Running',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md76',1,'']]],
  ['step_203_3a_20configure_20env_33',['Step 3: Configure .env',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md77',1,'']]],
  ['step_203_3a_20install_20python_20dependencies_34',['Step 3: Install Python Dependencies',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md14',1,'']]],
  ['step_203_3a_20set_20up_20postgresql_20user_20and_20database_35',['Step 3: Set Up PostgreSQL User and Database',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md55',1,'']]],
  ['step_204_3a_20set_20up_20postgresql_36',['Step 4: Set Up PostgreSQL',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md15',1,'']]],
  ['step_204_3a_20test_20connection_37',['Step 4: Test Connection',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md56',1,'']]],
  ['step_205_3a_20configure_20your_20env_20file_38',['Step 5: Configure Your .env File',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md57',1,'']]],
  ['step_205_3a_20verify_20setup_39',['Step 5: Verify Setup',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md16',1,'']]],
  ['step_206_3a_20initialize_20database_40',['Step 6: Initialize Database',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md17',1,'']]],
  ['step_206_3a_20initialize_20your_20database_41',['Step 6: Initialize Your Database',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md58',1,'']]],
  ['step_207_3a_20run_20example_42',['Step 7: Run Example',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md18',1,'']]],
  ['step_20by_20step_43',['Novice Setup (step-by-step)',['../md__r_e_a_d_m_e.html#autotoc_md98',1,'']]],
  ['steps_44',['Steps',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md43',1,'Next Steps'],['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md11',1,'Setup Steps']]],
  ['structure_45',['Project Structure',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md25',1,'']]],
  ['subsystem_20for_20linux_20recommended_20for_20you_46',['Option 1: WSL (Windows Subsystem for Linux) - RECOMMENDED FOR YOU',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md52',1,'']]],
  ['summary_20checklist_47',['Summary Checklist',['../md__g_e_t_t_i_n_g___s_t_a_r_t_e_d.html#autotoc_md47',1,'']]],
  ['system_20are_20you_20on_48',['Quick Detection - What System Are You On?',['../md__p_o_s_t_g_r_e_s_q_l___s_e_t_u_p___g_u_i_d_e.html#autotoc_md50',1,'']]]
];
