-- Seed task templates described in requirements.
-- Run manually via the SQL Query Execution tab.

CREATE TABLE IF NOT EXISTS task_templates (
  id text PRIMARY KEY,
  title text NOT NULL,
  category text NOT NULL,
  description text NOT NULL,
  classification jsonb NOT NULL,
  scheduling_options jsonb NOT NULL,
  allowed_frequencies jsonb NOT NULL,
  parameters jsonb NOT NULL,
  preconditions jsonb NOT NULL,
  postconditions jsonb NOT NULL,
  resources_required jsonb NOT NULL,
  time_estimate jsonb NOT NULL,
  cost_model jsonb NOT NULL,
  safety_level text NOT NULL,
  output_schema jsonb NOT NULL,
  quality_checks jsonb NOT NULL,
  retry_policy jsonb NOT NULL,
  concurrency_limits jsonb NOT NULL,
  visibility jsonb NOT NULL,
  virtual_effects jsonb NOT NULL,
  audit_fields_required jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO task_templates (
  id, title, category, description, classification, scheduling_options,
  allowed_frequencies, parameters, preconditions, postconditions,
  resources_required, time_estimate, cost_model, safety_level, output_schema,
  quality_checks, retry_policy, concurrency_limits, visibility, virtual_effects,
  audit_fields_required
) VALUES
(
  'hall_cleaning',
  'Hall Cleaning',
  'Cleaning',
  'Standard cleaning of apartment entrance/hall, includes dusting, sweeping, mopping, tidying shoes & surfaces.',
  '["recurring","requires-staff","on-site","light-equipment"]',
  '{"modes":["hourly","daily","weekly","custom"],"time_window":true}',
  '["hourly","daily","weekly","custom"]',
  '[{"name":"duration_minutes","type":"number","required":false,"default":30},{"name":"area_m2","type":"number","required":false},{"name":"intensity","type":"enum","required":false,"default":"standard","values":["light","standard","deep"]},{"name":"include_windows","type":"boolean","required":false,"default":false}]',
  '["user presence confirmed OR access instructions provided"]',
  '["floors swept","surfaces dusted","trash emptied"]',
  '{"staff":1,"equipment":["vacuum","mop","cleaning kit"]}',
  '{"min_minutes":20,"max_minutes":45}',
  '{"model":"flat","notes":"add-on pricing for include_windows"}',
  'low',
  '{"status":"string","actual_duration":"number","photos_before":[],"photos_after":[],"notes":"string","rating":"number"}',
  '["after-photo required","checklist: floors swept, surfaces dusted, trash emptied"]',
  '{"max_retries":1,"backoff":"fixed","escalation":"supervisor"}',
  '{"max_concurrent_per_entity":1}',
  '{"roles":["user","admin","contractor"]}',
  '[{"event":"cleaning_completed","effects":{"cleaning.last_cleaned":"timestamp","cleaning.score":"+computed"}}]',
  '["operator_id","start_time","end_time","photos"]'
),
(
  'vacuum_cleaning',
  'Vacuum Cleaning',
  'Cleaning',
  'Vacuum carpets & rugs; adjustable by suction level.',
  '["requires-staff","on-site"]',
  '{"modes":["on-demand","scheduled"],"time_window":true}',
  '["daily","weekly","custom"]',
  '[{"name":"rooms","type":"list","required":true},{"name":"duration_per_room","type":"number","required":false},{"name":"suction_level","type":"enum","required":false,"values":["low","med","high"]},{"name":"include_edges","type":"boolean","required":false,"default":false}]',
  '[]',
  '["carpets vacuumed","edges cleaned"]',
  '{"equipment":["vacuum","attachments"]}',
  '{"min_minutes":15,"max_minutes":90}',
  '{"model":"per-room","alternate":"per-hour"}',
  'low',
  '{"status":"string","photos_after":[],"notes":"string"}',
  '["1 photo per room (after)"]',
  '{"max_retries":1,"backoff":"fixed"}',
  '{"max_concurrent_per_entity":2}',
  '{"roles":["user","admin","contractor"]}',
  '[{"event":"vacuum_completed","effects":{"cleaning.score":"+computed"}}]',
  '["operator_id","start_time","end_time","photos"]'
),
(
  'deep_cleaning',
  'Deep Cleaning',
  'Cleaning',
  'Full apartment deep clean with detailed focus areas.',
  '["requires-2-staff","deep-equipment","longer-duration"]',
  '{"modes":["scheduled"],"time_window":true}',
  '["weekly","monthly","custom"]',
  '[{"name":"rooms","type":"list","required":true},{"name":"areas_to_focus","type":"list","required":false}]',
  '["confirm access","clear fragile items"]',
  '["before/after photos captured"]',
  '{"staff":2,"equipment":["vacuum","steam cleaner","cleaning kit"]}',
  '{"min_minutes":180,"max_minutes":480}',
  '{"model":"per-hour","minimum_hours":3}',
  'medium',
  '{"status":"string","photos_before":[],"photos_after":[],"notes":"string"}',
  '["before & after photos","optional supervisor verification"]',
  '{"max_retries":1,"backoff":"fixed"}',
  '{"max_concurrent_per_entity":1}',
  '{"roles":["user","admin"]}',
  '[{"event":"deep_cleaning_completed","effects":{"cleaning.last_deep_cleaned":"timestamp"}}]',
  '["operator_id","start_time","end_time","photos"]'
),
(
  'window_washing',
  'Window Washing',
  'Maintenance',
  'Interior and exterior window washing with safety checks.',
  '["requires-staff","high-safety","certification"]',
  '{"modes":["scheduled"],"time_window":true}',
  '["monthly","custom"]',
  '[{"name":"floors_high","type":"number","required":false},{"name":"interior_only","type":"boolean","required":false},{"name":"exterior_access_method","type":"string","required":false}]',
  '["approval required for exterior > 2nd floor"]',
  '["windows cleaned"]',
  '{"equipment":["squeegee","safety harness"]}',
  '{"min_minutes":45,"max_minutes":180}',
  '{"model":"per-window"}',
  'high',
  '{"status":"string","photos_after":[],"notes":"string"}',
  '["after-photo required"]',
  '{"max_retries":1,"backoff":"fixed"}',
  '{"max_concurrent_per_entity":1}',
  '{"roles":["admin","contractor"]}',
  '[{"event":"windows_cleaned","effects":{"windows.last_cleaned":"timestamp"}}]',
  '["operator_id","start_time","end_time","photos"]'
),
(
  'laundry_pickup_delivery',
  'Laundry Pickup & Delivery',
  'Logistics',
  'Pickup laundry bags and deliver after service completion.',
  '["requires-staff","logistics"]',
  '{"modes":["on-demand","recurring"],"time_window":true}',
  '["weekly","custom"]',
  '[{"name":"bag_count","type":"number","required":true},{"name":"service_type","type":"enum","required":true,"values":["wash-dry-fold","dryclean"]}]',
  '[]',
  '["items delivered"]',
  '{"staff":1,"equipment":["vehicle"]}',
  '{"min_minutes":30,"max_minutes":180}',
  '{"model":"per-bag","distance_surcharge":true}',
  'low',
  '{"pickup_time":"string","delivered_time":"string","items_processed_summary":"string"}',
  '["receipt or delivery photo"]',
  '{"max_retries":1,"backoff":"fixed"}',
  '{"max_concurrent_per_entity":3}',
  '{"roles":["user","admin","contractor"]}',
  '[{"event":"laundry_delivered","effects":{"laundry.last_service":"timestamp"}}]',
  '["operator_id","start_time","end_time","photos"]'
),
(
  'appliance_maintenance',
  'Appliance Maintenance',
  'Maintenance',
  'Appliance maintenance such as AC filter replacement.',
  '["requires-staff","certified"]',
  '{"modes":["scheduled"],"time_window":true}',
  '["monthly","custom"]',
  '[{"name":"appliance_type","type":"string","required":true},{"name":"model","type":"string","required":false},{"name":"part_required","type":"string","required":false},{"name":"warranty_check","type":"boolean","required":false}]',
  '["check warranty","confirm parts availability"]',
  '["maintenance completed"]',
  '{"staff":1,"equipment":["parts inventory"]}',
  '{"min_minutes":30,"max_minutes":120}',
  '{"model":"per-visit"}',
  'medium',
  '{"status":"string","replaced_parts":[],"serial_checked":"boolean","photos":[]}',
  '["photo of replaced part"]',
  '{"max_retries":1,"backoff":"fixed"}',
  '{"max_concurrent_per_entity":1}',
  '{"roles":["admin","contractor"]}',
  '[{"event":"appliance_serviced","effects":{"maintenance.last_service":"timestamp"}}]',
  '["operator_id","start_time","end_time","photos"]'
),
(
  'plumbing_inspection',
  'Plumbing Inspection & Fix',
  'Maintenance',
  'Plumbing inspection with emergency support.',
  '["emergency-capable","high-skill"]',
  '{"modes":["immediate","scheduled"],"time_window":true}',
  '["on-demand","custom"]',
  '[{"name":"issue_type","type":"enum","required":true,"values":["leak","clog"]},{"name":"severity","type":"enum","required":true,"values":["low","med","high"]}]',
  '["escalate immediately for high severity"]',
  '["issue resolved or follow-up scheduled"]',
  '{"staff":1,"equipment":["tools","parts"]}',
  '{"min_minutes":30,"max_minutes":180}',
  '{"model":"per-hour"}',
  'high',
  '{"status":"string","work_done":"string","parts_used":[],"follow_up_required":"boolean"}',
  '["photo evidence where possible"]',
  '{"max_retries":2,"backoff":"exponential","escalation":"supervisor"}',
  '{"max_concurrent_per_entity":1}',
  '{"roles":["admin","contractor","supervisor"]}',
  '[{"event":"plumbing_fixed","effects":{"plumbing.last_service":"timestamp"}}]',
  '["operator_id","start_time","end_time","photos"]'
),
(
  'pest_control',
  'Pest Control',
  'Maintenance',
  'Chemical treatment visits for pest control.',
  '["requires-chemical-license","high-safety"]',
  '{"modes":["scheduled"],"time_window":true}',
  '["monthly","custom"]',
  '[{"name":"pest_type","type":"string","required":true},{"name":"treatment_type","type":"string","required":true},{"name":"areas","type":"list","required":true}]',
  '["vacate for X hours","pet safety instructions delivered"]',
  '["treatment complete","recheck scheduled"]',
  '{"staff":1,"equipment":["treatment chemicals","PPE"]}',
  '{"min_minutes":60,"max_minutes":240}',
  '{"model":"per-visit"}',
  'high',
  '{"treatment_done":"boolean","recheck_suggested_date":"string"}',
  '["photo of treatment areas"]',
  '{"max_retries":1,"backoff":"fixed"}',
  '{"max_concurrent_per_entity":1}',
  '{"roles":["admin","contractor","supervisor"]}',
  '[{"event":"pest_treated","effects":{"pest.last_treatment":"timestamp"}}]',
  '["operator_id","start_time","end_time","photos"]'
),
(
  'lawn_garden_care',
  'Lawn/Garden Mowing & Care',
  'Outdoor Maintenance',
  'Seasonal lawn and garden mowing with optional fertilization.',
  '["requires-staff","outdoor"]',
  '{"modes":["scheduled"],"time_window":true}',
  '["weekly","biweekly","custom"]',
  '[{"name":"mow_height","type":"number","required":false},{"name":"edging","type":"boolean","required":false},{"name":"fertilization","type":"boolean","required":false}]',
  '[]',
  '["lawn trimmed","edges clean"]',
  '{"equipment":["mower","trimmer"]}',
  '{"min_minutes":45,"max_minutes":180}',
  '{"model":"per-visit"}',
  'low',
  '{"status":"string","photos_after":[]}',
  '["after-photo required"]',
  '{"max_retries":1,"backoff":"fixed"}',
  '{"max_concurrent_per_entity":2}',
  '{"roles":["user","admin","contractor"]}',
  '[{"event":"lawn_cared","effects":{"lawn.last_mowed":"timestamp"}}]',
  '["operator_id","start_time","end_time","photos"]'
),
(
  'grocery_delivery',
  'Grocery or Errand Delivery',
  'Logistics',
  'Errand delivery with budget controls.',
  '["requires-staff","logistics"]',
  '{"modes":["immediate","scheduled"],"time_window":true}',
  '["on-demand","custom"]',
  '[{"name":"items","type":"list","required":true},{"name":"budget_limit","type":"number","required":true},{"name":"preferred_shops","type":"list","required":false}]',
  '["user authorization to purchase"]',
  '["items delivered"]',
  '{"staff":1,"equipment":["vehicle"]}',
  '{"min_minutes":30,"max_minutes":120}',
  '{"model":"service_fee","notes":"item cost + tip"}',
  'low',
  '{"status":"string","receipt_photos":[]}',
  '["receipt or delivery photo"]',
  '{"max_retries":1,"backoff":"fixed"}',
  '{"max_concurrent_per_entity":3}',
  '{"roles":["user","admin","contractor"]}',
  '[{"event":"delivery_complete","effects":{"delivery.last_delivery":"timestamp"}}]',
  '["operator_id","start_time","end_time","photos"]'
),
(
  'medication_reminder',
  'Medication Reminder & Admin Tasks',
  'Health/Admin',
  'Medication reminders with optional escalation.',
  '["automated","privacy-high"]',
  '{"modes":["scheduled"],"time_window":false}',
  '["daily","custom"]',
  '[{"name":"medication_name","type":"string","required":true},{"name":"dose","type":"string","required":true},{"name":"times","type":"list","required":true},{"name":"confirm_required","type":"boolean","required":false}]',
  '["user consent recorded"]',
  '["reminder sent"]',
  '{"staff":0}',
  '{"min_minutes":1,"max_minutes":5}',
  '{"model":"subscription"}',
  'medium',
  '{"status":"string","acknowledged":"boolean"}',
  '["acknowledgement logged"]',
  '{"max_retries":2,"backoff":"fixed","escalation":"supervisor"}',
  '{"max_concurrent_per_entity":10}',
  '{"roles":["user","admin","supervisor"]}',
  '[{"event":"medication_reminded","effects":{"health.last_reminder":"timestamp"}}]',
  '["operator_id","start_time","end_time"]'
),
(
  'smart_home_update',
  'Smart-Home Software Update',
  'IT/Remote',
  'Remote firmware update for smart-home devices.',
  '["automated","remote-only"]',
  '{"modes":["scheduled"],"time_window":true}',
  '["weekly","custom"]',
  '[{"name":"device_ids","type":"list","required":true},{"name":"firmware_version","type":"string","required":true},{"name":"maintenance_window","type":"string","required":false}]',
  '["device online","backup present"]',
  '["updates completed"]',
  '{"staff":0}',
  '{"min_minutes":10,"max_minutes":60}',
  '{"model":"flat"}',
  'low',
  '{"updated_devices":[],"failed_devices":[]}',
  '["status reported"]',
  '{"max_retries":2,"backoff":"exponential"}',
  '{"max_concurrent_per_entity":5}',
  '{"roles":["admin","supervisor"]}',
  '[{"event":"firmware_updated","effects":{"devices.last_update":"timestamp"}}]',
  '["operator_id","start_time","end_time","logs"]'
),
(
  'package_pickup',
  'Package Pickup / Verification',
  'Logistics',
  'Package pickup with verification and signature.',
  '["requires-staff","logistics"]',
  '{"modes":["on-demand","scheduled"],"time_window":true}',
  '["on-demand","custom"]',
  '[{"name":"carrier","type":"string","required":true},{"name":"tracking_number","type":"string","required":true}]',
  '["user authorization to sign/receive"]',
  '["package delivered"]',
  '{"staff":1}',
  '{"min_minutes":15,"max_minutes":60}',
  '{"model":"per-visit"}',
  'low',
  '{"collected":"boolean","signature_image":"string","delivered_to":"string"}',
  '["signature captured"]',
  '{"max_retries":1,"backoff":"fixed"}',
  '{"max_concurrent_per_entity":2}',
  '{"roles":["user","admin","contractor"]}',
  '[{"event":"package_collected","effects":{"delivery.last_package":"timestamp"}}]',
  '["operator_id","start_time","end_time","signature"]'
)
ON CONFLICT (id) DO NOTHING;
